--Employees
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172148,	'James Dulgerian',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172281,	'Xeng Moua',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172336,	'John Cabigao',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172363,	'Carlos Velasquez',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172787,	'Kevin Fang',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172813,	'Leonel Aguilera',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172872,	'Daniel Vega',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172889,	'Nathan Vargo',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172906,	'Austin Danaj',	0,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172909,	'Joseph Kielasa',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172915,	'Osamu Inoue',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172923,	'Levi Hellebuyck',	0,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172945,	'Cruz España',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172947,	'Damien Galloway',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172981,	'Hugo Moran',	1,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172990,	'Francesco Parrinelio',	0,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (172991,	'Seth Logan',	0,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (173017,	'Anthony Hewins',	0,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (173018,	'Zarif Ghazi',	0,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (173036,	'Fabrisio Ballo',	0,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (173037,	'Chad Miller',	0,	1);
INSERT into Employees (Alna_num, Name, Full_time, Active) VALUES (173039,	'Benjamin Thelen',	0,	1);

--Projects;
INSERT into Projects (Name, Category, Active) VALUES ('BLE_PEPS_High_Accuracy',	'A',	1);
INSERT into Projects (Name, Category, Active) VALUES ('BLE_TPMS',	'A',	1);
INSERT into Projects (Name, Category, Active) VALUES ('Technology_Research',	'A',	1);
INSERT into Projects (Name, Category, Active) VALUES ('General_CTB',	'A',	1);
INSERT into Projects (Name, Category, Active) VALUES ('POC',	'A',	1);
INSERT into Projects (Name, Category, Active) VALUES ('BLE_Key_Pass_Global_A',	'C',	1);
INSERT into Projects (Name, Category, Active) VALUES ('BLE_Key_Pass_Global_A_Testing',	'C',	1);
INSERT into Projects (Name, Category, Active) VALUES ('BLE_Key_Pass_Global_B',	'C',	1);
INSERT into Projects (Name, Category, Active) VALUES ('BLE_Key_Pass_Autonomus',	'C',	1);
INSERT into Projects (Name, Category, Active) VALUES ('USRR_Track_3',	'C',	1);
INSERT into Projects (Name, Category, Active) VALUES ('M2R',	'A',	1);
INSERT into Projects (Name, Category, Active) VALUES ('MMR',	'A',	1);
INSERT into Projects (Name, Category, Active) VALUES ('USRR_2',	'A',	1);
INSERT into Projects (Name, Category, Active) VALUES ('Smart_Thermostat',	'D',	1);
INSERT into Projects (Name, Category, Active) VALUES ('IR_Transmitter',	'D',	1);
INSERT into Projects (Name, Category, Active) VALUES ('Multipurpose_Sensor',	'A',	1);
INSERT into Projects (Name, Category, Active) VALUES ('Vacations',	'B',	1);
;
--Phones;
insert into Phones (Name, Active) values ('iPhone 6-1');
insert into Phones (Name, Active) values ('iPhone 6P-1');
insert into Phones (Name, Active) values ('iPhone 5S-1');
insert into Phones (Name, Active) values ('iPhone 6S-1');
insert into Phones (Name, Active) values ('iPhone 7-1');
insert into Phones (Name, Active) values ('iPhone 6S-2');
insert into Phones (Name, Active) values ('Galaxy S6-1');
insert into Phones (Name, Active) values ('Galaxy S5-4');
insert into Phones (Name, Active) values ('Galaxy S5-3');
insert into Phones (Name, Active) values ('Galaxy S6-2');
insert into Phones (Name, Active) values ('Galaxy S6-3');
insert into Phones (Name, Active) values ('Galaxy S5-1');
insert into Phones (Name, Active) values ('Galaxy S7 Edge-1');
insert into Phones (Name, Active) values ('Galaxy S7 Edge-2');
insert into Phones (Name, Active) values ('Galaxy S7 Edge-3');
insert into Phones (Name, Active) values ('Galaxy S7-1');
insert into Phones (Name, Active) values ('Galaxy S7-2');
insert into Phones (Name, Active) values ('Tablet-1');
insert into Phones (Name, Active) values ('Tablet-2');
insert into Phones (Name, Active) values ('Big Nexus');
insert into Phones (Name, Active) values ('Lil Nexus');
;
--Accounts;
insert into Accounts (Accounts.[User], Pass, Admin) values (1,	'User',	'alna',	0);
insert into Accounts (Accounts.[User], Pass, Admin) values (2,	'Admin',	'alnatest',	1)